nyt_word_bubble/models.py
from . import db

# SQLAlchemy model for the word frequency table
class WordFrequencyWeek(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(30))
    frequency = db.Column(db.Integer)


class WordFrequencyDay(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(30))
    frequency = db.Column(db.Integer)

nyt_word_bubble/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import config

import logging

db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class='default'):
    app = Flask(__name__)
    app.config.from_object(config[config_class])
    config[config_class].init_app(app)

    app.logger.setLevel(logging.DEBUG)

    from .main import bp as main_bp
    app.register_blueprint(main_bp)

    from .api import bp as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api/v0')

    db.init_app(app)
    migrate.init_app(app, db)

    return app

from . import models

nyt_word_bubble/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from . import errors, routes, main

nyt_word_bubble/api/main.py
from flask import current_app
import requests
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nyt_word_bubble import db
import os
import numpy as np


nltk.download("punkt")
nltk.download("stopwords")


def fetch_nytimes_articles(period=1):
    api_key = current_app.config['NYT_API_KEY']
    url = f"https://api.nytimes.com/svc/mostpopular/v2/viewed/{period}.json?api-key={api_key}"

    response = requests.get(url)

    if response.status_code == 200:
        articles = response.json()["results"]
        top50 = process_articles(articles)

        return top50
    else:
        print(f"Error fetching articles: {response.status_code}")


def write_nyt_to_db(table, top50):
    with current_app.app_context():
        # flush prev table
        table.query.delete()
        db.session.commit()

        for i, word_dic in enumerate(top50):
            word = table(
                id=i + 1, word=word_dic["word"], frequency=int(word_dic["frequency"])
            )
            db.session.add(word)
            db.session.commit()


def process_articles(articles):
    all_words = []
    stop_words = set(stopwords.words("english"))

    for article in articles:
        # Extract the article content
        content = f"{article['title']}\n{article['abstract']}"

        # Tokenize the content
        words = word_tokenize(content)

        # Remove stopwords and non-alphanumeric characters
        words = [
            word.lower()
            for word in words
            if word.isalnum() and word.lower() not in stop_words
        ]

        # Add the words to the list
        all_words.extend(words)

    # Count the frequency of each word
    word_counts = np.unique(all_words, return_counts=True)

    # Sort the words based on their frequency
    sorted_indices = np.argsort(word_counts[1])[::-1]

    # Get the top 50 most frequent words and their frequencies
    top_50_words = word_counts[0][sorted_indices][:50]
    top_50_frequencies = word_counts[1][sorted_indices][:50]

    # Convert the words and frequencies to a list of dictionaries
    word_frequency_list = [
        {"word": word, "frequency": freq}
        for word, freq in zip(top_50_words, top_50_frequencies)
    ]

    return word_frequency_list

nyt_word_bubble/api/routes.py
from flask import jsonify, current_app
from . import bp as api

from .main import fetch_nytimes_articles, write_nyt_to_db
from nyt_word_bubble.models import WordFrequencyDay, WordFrequencyWeek

@api.route("/word_bubble_data_week")
def word_bubble_data_week():
    words = WordFrequencyWeek.query.all()

    if len(words) == 0:
        top50 = fetch_nytimes_articles(period=7)
        write_nyt_to_db(WordFrequencyWeek, top50)

    words = [
        {"id": i.id, "word": i.word, "frequency": i.frequency}
        for i in WordFrequencyWeek.query.all()
    ]

    return jsonify(words)


@api.route("/word_bubble_data_day")
def word_bubble_data_day():
    words = WordFrequencyDay.query.all()

    if len(words) == 0:
        top50 = fetch_nytimes_articles(period=1)
        write_nyt_to_db(WordFrequencyDay, top50)

    words = [
        {"id": i.id, "word": i.word, "frequency": i.frequency}
        for i in WordFrequencyDay.query.all()
    ]

    return jsonify(words)

nyt_word_bubble/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import routes, errors

nyt_word_bubble/main/routes.py
import os
from flask import (
    render_template,
)
from . import bp as main
from werkzeug.http import HTTP_STATUS_CODES

basedir = os.path.abspath(os.path.dirname(__file__))

@main.route("/")
def index():
    return render_template("index.html")

@main.route("/info")
def info():
    return "<h1>TO-DO</h1>"

nyt_word_bubble/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NYTimes Word Bubble</title>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3-cloud/1.2.5/d3.layout.cloud.js"></script>
    <link rel="stylesheet" href="/static/css/tailwind.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
</head>

<body class="bg-gray-100 font-sans">
    <div id="container" class="max-w-3xl mx-auto py-10 px-6 bg-white shadow-lg rounded-lg mt-10">
        <h1 class="font-serif text-4xl font-bold mb-6 text-blue-700 text-center">New York Times Top 50 Word Bubble</h1>
        <h2 class="text-lg text-gray-600 mb-6 text-center">This visualization represents the top 50 most frequently appearing words in the most popular titles and abstracts of articles
            viewed on The New York Times of the past day and week.</h2>
        <h3 class="text-base text-gray-500 mb-6 text-center">Data Source: <a
                href="https://developer.nytimes.com/docs/most-popular-product/1/routes/viewed/%7Bperiod%7D.json/get"
                class="text-blue-700">NYTimes Most Viewed API</a></h3>

        <div class="flex flex-col items-center m-auto">
            <div class="flex items-center mb-6 justify-center">
                <input type="checkbox" id="toggle" name="view" value="week" class="hidden">
                <label for="toggle" class="bg-indigo-300 w-14 h-8 rounded-full px-1 flex items-center cursor-pointer"
                    id="toggleButtonLabel">
                    <div id="toggleBall" class="bg-white w-6 h-6 rounded-full shadow-md transform duration-300"></div>
                </label>
                <span class="ml-2 text-sm font-bold" id="toggleLabel">Yesterday</span>
            </div>
            <div id="word-bubble" class="w-[95%] h-[400px] bg-gray-100 rounded shadow-lg font-semibold"></div>
        </div>
        <div class="p-4">
            <h2 class="text-xl font-bold mb-4">API routes for JSON responses:</h2>
            <ul class="list-disc pl-8">
              <li>api/v0/word_bubble_data_day</li>
              <li>api/v0/word_bubble_data_week</li>
            </ul>
          </div>
    </div>
    <script>
        const dayUrl = '{{ url_for("api.word_bubble_data_day") }}';
        const weekUrl = '{{ url_for("api.word_bubble_data_week") }}';
    </script>
    <script src="/static/js/word_bubble.js"></script>

      
</body>

</html>